version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt-preview
            rustup update
      - run:
          name: Install crates
          command: cargo install chisel wasm-gc wasm-snip
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt
            git diff --exit-code
      - run:
          name: Build
          command: make
      - run:
          name: Tests
          command: cargo test
